package info.mobinaheidari.routerunner.data.local

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents the `users` table in the local Room database.
 *
 * This entity defines the schema for storing user profile and authentication credentials.
 *
 * **Key Constraints:**
 * - **Primary Key:** [id] is auto-generated by Room.
 * - **Unique Index:** The [username] column is indexed with `unique = true`. This prevents
 * duplicate user registrations at the database level, ensuring data integrity.
 *
 * @property id The unique identifier for the user row. Set to 0 for auto-generation during insertion.
 * @property firstName The user's first name.
 * @property lastName The user's last name.
 * @property age The user's age.
 * @property birthDate The user's birth date, stored as a String (format: YYYY-MM-DD).
 * @property username The unique login identifier.
 * @property password The user's authentication credential.
 *
 */
@Entity(
    tableName = "users",
    indices = [Index(value = ["username"], unique = true)] // Enforces uniqueness at the SQLite level
)
data class UserEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val firstName: String,
    val lastName: String,
    val age: Int,
    val birthDate: String,
    val username: String,
    val password: String
)